/* 
© 2025 Aravinth Raj R. All rights reserved.
Unauthorized copying of this file, via any medium, is strictly prohibited.
Proprietary and confidential.  
Written by Aravinth Raj R <aravinthr235@gmail.com>, 2025.
*/
export const SALES_CONFIG = {
  search: "Search",
  serial: "Sl No.",
  productName: "Product Name",
  category: "Category",
  quantity: "Quantity",
  mrp: "MRP",
  date: "Date : ",
  prMRP: "Total Sales: ₹ ",
  from: "From : ",
  to: "To : ",
  itemsSold: "Total Items Sold : ",
  downloadButton: "Download Report",
  sortedOptions: ["Sort By Title Asc", "Sort By Title Desc"],
  all: "All",
  title: [
    "Sl.No",
    "Category",
    "Product Name",
    "Sold",
    "Left",
    "Total Amount(in Rs.)",
  ],
  salesItems: [
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
  ],
};
