import { SlActionRedo } from "react-icons/sl";

/* 
© 2025 Aravinth Raj R. All rights reserved.
Unauthorized copying of this file, via any medium, is strictly prohibited.
Proprietary and confidential.  
Written by Aravinth Raj R <aravinthr235@gmail.com>, 2025.
*/
export const SALES_CONFIG = {
  AddCategoryTitle: "Add Category",
  Serial: "Sl No.",
  ProductName: "Product Name",
  Category: "Category",
  Quantity: "Quantity",
  MRP: "MRP",
  OrderNumber: "Order Number : ",
  OrderBy: "Order By : ",
  Date: "Date : ",
  PrMRP: "Total : ₹ ",
  DeleteButton: "Delete",
  AmountRecieved: "Amount Recieved",
  Deliver: "Deliver",
  viewButton: "View",
  Delete: "Delete",
  sortedOptions: ["Sort By Title Asc", "Sort By Title Desc"],
  All: "All",
  Title: ["Sl.No", "Category", "Product Name", "Sold", "Left", "Total Amount"],
  salesItems: [
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
    {
      Sl_No: 1,
      Category: "Stationary",
      Product_Name: "TagFile",
      Sold: 2,
      Left: 3,
      Total_Amount: 1000,
    },
  ],
};
